import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GitHubLink from './ui/GitHubLink';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased p-4 h-dvh w-dvw ${inter.className}`}>
        <div className="text-right px-4 sm:px-6">
          <GitHubLink />
        </div>
        {children}
      </body>
    </html>
  );
}
