import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GitHubLink from './ui/GitHubLink';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased h-dvh w-dvw ${inter.className}`}>
        <div className="fixed top-0 left-0 w-full text-right pt-4 px-5">
          <GitHubLink />
        </div>
        {children}
        <div className="fixed bottom-0 left-0 w-full text-xs text-gray-400">
          <div className="ml-auto mr-auto max-w-xs pb-4 px-5 flex justify-between items-center">
            <span>START = Power on</span>
            <span>SELECT = Settings</span>
          </div>
        </div>
      </body>
    </html>
  );
}
